services:
  - type: web
    name: BMasterMart
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_PORT
        value: 3307
      - key: PHP_VERSION
        value: 8.2.12
